// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrategyGame.Data;

#nullable disable

namespace StrategyGame.Migrations
{
    [DbContext(typeof(StrategyGameContext))]
    [Migration("20250508151028_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackPackItem", b =>
                {
                    b.Property<int>("BackPackId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("BackPackId", "ItemId")
                        .HasName("PK__BackPack__3759BBF93E100BE8");

                    b.HasIndex("ItemId");

                    b.ToTable("BackPackItem", (string)null);
                });

            modelBuilder.Entity("StrategyGame.Models.Armor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DefensePercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id")
                        .HasName("PK__Armor__3214EC076A9415A6");

                    b.ToTable("Armor", (string)null);
                });

            modelBuilder.Entity("StrategyGame.Models.Backpack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Backpack__3214EC07514A6DB0");

                    b.HasIndex(new[] { "HeroId" }, "UQ_Backpack_Heroid")
                        .IsUnique();

                    b.ToTable("Backpack", (string)null);
                });

            modelBuilder.Entity("StrategyGame.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquippedArmor")
                        .HasColumnType("int");

                    b.Property<int?>("EquippedWeapon")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Health")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8, 2)")
                        .HasDefaultValue(100m);

                    b.Property<bool>("IsDead")
                        .HasColumnType("bit");

                    b.Property<int?>("LegionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id")
                        .HasName("PK__Hero__3214EC076E97809B");

                    b.HasIndex("EquippedArmor");

                    b.HasIndex("EquippedWeapon");

                    b.HasIndex("LegionId");

                    b.ToTable("Hero", (string)null);
                });

            modelBuilder.Entity("StrategyGame.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Item__3214EC0785D3B0CE");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("StrategyGame.Models.Legion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id")
                        .HasName("PK__Legion__3214EC07A9651F52");

                    b.ToTable("Legion", (string)null);
                });

            modelBuilder.Entity("StrategyGame.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Damage")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Monster__3214EC078720EC3B");

                    b.ToTable("Monster", (string)null);
                });

            modelBuilder.Entity("StrategyGame.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Damage")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id")
                        .HasName("PK__Weapon__3214EC07D51BCEBC");

                    b.ToTable("Weapon", (string)null);
                });

            modelBuilder.Entity("BackPackItem", b =>
                {
                    b.HasOne("StrategyGame.Models.Backpack", null)
                        .WithMany()
                        .HasForeignKey("BackPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BackPackItem_Backpack");

                    b.HasOne("StrategyGame.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BackPackItem_Item");
                });

            modelBuilder.Entity("StrategyGame.Models.Backpack", b =>
                {
                    b.HasOne("StrategyGame.Models.Hero", "Hero")
                        .WithOne("Backpack")
                        .HasForeignKey("StrategyGame.Models.Backpack", "HeroId")
                        .IsRequired()
                        .HasConstraintName("FK_Backpack_Hero");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("StrategyGame.Models.Hero", b =>
                {
                    b.HasOne("StrategyGame.Models.Armor", "EquippedArmorNavigation")
                        .WithMany("Heroes")
                        .HasForeignKey("EquippedArmor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Hero_Armor");

                    b.HasOne("StrategyGame.Models.Weapon", "EquippedWeaponNavigation")
                        .WithMany("Heroes")
                        .HasForeignKey("EquippedWeapon")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Hero_Weapon");

                    b.HasOne("StrategyGame.Models.Legion", "Legion")
                        .WithMany("Heroes")
                        .HasForeignKey("LegionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Hero_Legion");

                    b.Navigation("EquippedArmorNavigation");

                    b.Navigation("EquippedWeaponNavigation");

                    b.Navigation("Legion");
                });

            modelBuilder.Entity("StrategyGame.Models.Armor", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("StrategyGame.Models.Hero", b =>
                {
                    b.Navigation("Backpack");
                });

            modelBuilder.Entity("StrategyGame.Models.Legion", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("StrategyGame.Models.Weapon", b =>
                {
                    b.Navigation("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
